# Generated by Django 2.1.11 on 2019-11-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_selected',
        ),
    ]
