# Generated by Django 2.2.6 on 2019-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlive', '0002_auto_20191103_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='encrypt',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
