# Generated by Django 2.2.6 on 2019-11-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlive', '0003_auto_20191103_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='encrypt',
        ),
    ]
